{"name": "Test Valid Credentials", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Locators' has no attribute 'error_invalid_credentials'", "trace": "self = <paraBank_test.TestParaBank object at 0x00000159CC519F30>\n\n    @pytest.mark.login\n    @allure.title(\"Test Valid Credentials\")\n    @allure.description(\"Logs in with valid credentials and verifies that the account overview is visible.\")\n    def test_valid_login(self):\n>       self.pb.valid_login()\n\ntestcases\\paraBank_test.py:74: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.paraBank_page.ParaBankPage object at 0x00000159CC68DA90>\n\n    @allure.step(\"Validating login with valid credentials\")\n    def valid_login(self):\n        self.get_element(self.Locators.VALID_USERNAME).send_keys(self.userName)\n        self.get_element(self.Locators.VALID_PASSWORD).send_keys(self.password)\n        self.click_on_element(self.Locators.LOGIN_BUTTON)\n        landing_page= self.get_element((By.NAME, \"showOverview\"))\n        sleep(2)\n>       if self.is_element_visible(self.Locators.error_invalid_credentials):\n                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       AttributeError: type object 'Locators' has no attribute 'error_invalid_credentials'\n\npages\\paraBank_page.py:125: AttributeError"}, "description": "Logs in with valid credentials and verifies that the account overview is visible.", "steps": [{"name": "Validating login with valid credentials", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Locators' has no attribute 'error_invalid_credentials'\n", "trace": "  File \"C:\\vsCode\\parabank_credentials\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\vsCode\\parabank_credentials\\pages\\paraBank_page.py\", line 125, in valid_login\n    if self.is_element_visible(self.Locators.error_invalid_credentials):\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1751149972282, "stop": 1751149986722}], "attachments": [{"name": "screenshot", "source": "4b9e9ba6-74ff-4750-8f83-42313c2a0922-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "28a9f2d9-55de-4703-89c0-0ecad5eb24ec-attachment.txt", "type": "text/plain"}], "start": 1751149972282, "stop": 1751149986727, "uuid": "4455fc87-4f8a-4df7-95e0-fcc564c2c373", "historyId": "b02c000aaec4e3b1734b87abde7050f5", "testCaseId": "b02c000aaec4e3b1734b87abde7050f5", "fullName": "testcases.paraBank_test.TestParaBank#test_valid_login", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "paraBank_test"}, {"name": "subSuite", "value": "TestParaBank"}, {"name": "host", "value": "Hans"}, {"name": "thread", "value": "7480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.paraBank_test"}]}