{"name": "Test Valid Credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Username field not found", "trace": "self = <paraBank_test.TestParaBank object at 0x0000020B1D700CD0>\n\n    @pytest.mark.login\n    @allure.title(\"Test Valid Credentials\")\n    @allure.description(\"Logs in with valid credentials and verifies that the account overview is visible.\")\n    def test_valid_login(self):\n>       self.pb.valid_login()\n\ntestcases\\paraBank_test.py:57: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\paraBank_page.py:137: in valid_login\n    raise e\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.paraBank_page.ParaBankPage object at 0x0000020B1D701090>\n\n    @allure.step(\"Login using username and password\")\n    def valid_login(self):\n        try:\n            username_field = self.get_element(self.Locators.VALID_USERNAME)\n            password_field = self.get_element(self.Locators.VALID_PASSWORD)\n    \n>           assert username_field is not None, \"Username field not found\"\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^\nE           AssertionError: Username field not found\n\npages\\paraBank_page.py:122: AssertionError"}, "description": "Logs in with valid credentials and verifies that the account overview is visible.", "steps": [{"name": "Login using username and password", "status": "failed", "statusDetails": {"message": "AssertionError: Username field not found\n", "trace": "  File \"C:\\vsCode\\parabank_credentials\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 202, in impl\n    return func(*a, **kw)\n  File \"C:\\vsCode\\parabank_credentials\\pages\\paraBank_page.py\", line 137, in valid_login\n    raise e\n  File \"C:\\vsCode\\parabank_credentials\\pages\\paraBank_page.py\", line 122, in valid_login\n    assert username_field is not None, \"Username field not found\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "attachments": [{"name": "Login Failure Screenshot", "source": "da0c6077-40cd-4d7d-b31d-f34ba6d25252-attachment.png", "type": "image/png"}], "start": 1751160385077, "stop": 1751160405336}], "attachments": [{"name": "screenshot", "source": "fc06ac67-c90c-441c-8316-9349ad1c27c0-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "e27bbeeb-88f6-4fd1-ae73-675998e5f929-attachment.txt", "type": "text/plain"}], "start": 1751160385077, "stop": 1751160405339, "uuid": "76c9b8b6-85eb-41f1-bf0e-3c0080f0dcd1", "historyId": "b02c000aaec4e3b1734b87abde7050f5", "testCaseId": "b02c000aaec4e3b1734b87abde7050f5", "fullName": "testcases.paraBank_test.TestParaBank#test_valid_login", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "paraBank_test"}, {"name": "subSuite", "value": "TestParaBank"}, {"name": "host", "value": "Hans"}, {"name": "thread", "value": "12400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.paraBank_test"}]}